server.port=8080
spring.application.name=ms-gateway

# Registro en Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
#ppt
# Configuración de Rutas
# Todo lo que llegue a http://localhost:8080/auth/... se va al MS-SEGURIDAD
spring.cloud.gateway.routes[0].id=ms-seguridad
spring.cloud.gateway.routes[0].uri=lb://MS_SEGURIDAD
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**