server:
port: 9099

spring:
application:
name: MS_seguridad

# Configuración de Base de Datos
datasource:
url: jdbc:mysql://localhost:3306/db_seguridad?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL=false
username: root
password: "" # Pon tu contraseña de MySQL aquí si tienes
driver-class-name: com.mysql.cj.jdbc.Driver

# Configuración de JPA / Hibernate
jpa:
hibernate:
ddl-auto: validate # Flyway se encarga de la estructura
show-sql: true
properties:
hibernate:
format_sql: true
dialect: org.hibernate.dialect.MySQLDialect

# Configuración de Flyway
flyway:
enabled: true
baseline-on-migrate: true
locations: classpath:db/migration

# Configuración de Seguridad personalizada (JWT)
jwt:
# Clave secreta segura (HMAC-SHA256)
secret: "404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970"
# Expira en 24 horas (en milisegundos)
expiration: 86400000

# Registro en el servidor Eureka
eureka:
client:
service-url:
defaultZone: http://localhost:8761/eureka/
fetch-registry: true
register-with-eureka: true
instance:
prefer-ip-address: true